### ISSUE TITLE
Wallet is limited to 20000 transfer

### ISSUE THREAD

**Issue by barrettathome** [CMUSICAI/Cmusic#3]

**Comment by HomelessPhD** [comment]
Are you sure the problem "it is limited to 20 000 coins in 1 tx" and not some "data size" limit on a tx?

I suspect you have tried to make tx with ALOT of small inputs  - spending each input meaning placing a specific "sigscript" into the tx AND it has a size, when you have lots of inputs being spent in single tx the size of that tx could became large. Most of cryptos have the limitations. Have you heard about the war between 1 MB block size and 2 MB block size on BTC?

Yep thats the thing - it is related. I have transferred, if i remember, more than 20 000 coins at once - just with larger input tx.

**Comment by barrettathome** [comment]
> Are you sure the problem "it is limited to 20 000 coins in 1 tx" and not some "data size" limit on a tx?
> 
> I suspect you have tried to make tx with ALOT of small inputs - spending each input meaning placing a specific "sigscript" into the tx AND it has a size, when you have lots of inputs being spent in single tx the size of that tx could became large. Most of cryptos have the limitations. Have you heard about the war between 1 MB block size and 2 MB block size on BTC?
> 
> Yep thats the thing - it is related. I have transferred, if i remember, more than 20 000 coins at once - just with larger input tx.

Hmm yea I haven't heard about that before.  To be honest I haven't had the time to dig in and troubleshoot the issue :)

I know the daemon doesn't have an issue sending more than 20k so I thought it was a limitation on the wallet/GUI.

**Comment by HomelessPhD** [comment]
well.... maybe there is some else factor

Any other faced that problem?

**Comment by barrettathome** [comment]
> well.... maybe there is some else factor
> 
> Any other faced that problem?

So far I've only experienced it, haven't heard of anyone else having this issue but I can check around to confirm.

**Comment by barrettathome** [comment]
After careful consideration, we've determined that this is not an issue and we will keep the max send at 20k coins for the wallet GUI.  Since users can still send through the RPC we will create a guide for that.

Ticket: https://cmusicai.atlassian.net/browse/CMS-5

**Comment by kindlyman343423** [comment]
so, this ticket closed?

**Comment by barrettathome** [comment]
Correct
